# -*- coding: utf-8 -*-
"""Circle Area Finder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wkZwxT0IBwEFqws_ErPOClb4l6CSnAqn
"""

import math
import numpy as np

import numpy as np
import matplotlib.pyplot as plt
import math
circle_counts = int(input("How many circles do you want ? "))

for i in range(circle_counts):
   n = input("Please enter coordinates of center and radius ").split()
   x, y, r = map(int, n)
   center = (x,y)
   theta = np.linspace(0, 2*np.pi, 100)
   x1 = center[0] + r * np.cos(theta)
   y1 = center[1] + r * np.sin(theta)
   plt.plot(x1,y1, 'b-')
   plt.axis('equal')
   plt.grid(visible= True, axis ='both')
   plt.xlabel('X-Axis')
   plt.ylabel('Y-Axis')
   area = np.pi * r**2
   circumference = 2*np.pi*r
   print('Area of Circle: ', area)
   print('Area of Circumference', circumference)



